name: FEEL Bug Report
description: Report a problem and help us fix it.
labels: ["kind/bug", "area/feel", "component/feel-scala", "component/feel-js"]
assignees: ["saig0"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-reproduction
    attributes:
      label: Steps to reproduce
      description: Clear steps that allow us to reproduce the error. Or, a link to a FEEL playground.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen. Link to the DMN specification if possible.
    validations:
      required: true
  - type: dropdown
    id: feel-engine
    attributes:
      label: FEEL-Engine
      description: The FEEL engine on which this error was observed.
      multiple: true
      options:
        - FEEL-Scala (Runtime, Expressions, DMN)
        - FEEL-JS (Modeler, Forms)
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: 'The environment on which this error was observed.'
      value: |
             - Camunda Version: [e.g. 8.6.0]
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else that might help us to evaluate the error.
    validations:
      required: false
