name: Camunda Helm Chart Integration Test

on:
  schedule:
    - cron: "0 5 * * *"
  pull_request:
    paths:
      - ".github/workflows/camunda-helm-integration.yml"
  workflow_dispatch:

jobs:
  helm-deploy:
    name: Helm chart Integration Tests
    uses: camunda/camunda-platform-helm/.github/workflows/test-integration-template.yaml@main
    secrets: inherit
    with:
      identifier: camunda-helm-int
      camunda-helm-dir: camunda-platform-alpha-8.8
      test-enabled: true
      caller-git-ref: main
      extra-values: |
        zeebe:
          image:
            tag: SNAPSHOT
        operate:
          image:
            tag: SNAPSHOT
        tasklist:
          image:
            tag: SNAPSHOT
        optimize:
          image:
            tag: 8-SNAPSHOT
      vault-secret-mapping: |
        secret/data/products/zeebe/ci/zeebe REGISTRY_HUB_DOCKER_COM_USR | TEST_DOCKER_USERNAME;
        secret/data/products/zeebe/ci/zeebe REGISTRY_HUB_DOCKER_COM_PSW | TEST_DOCKER_PASSWORD;
        secret/data/github.com/organizations/camunda NEXUS_USR | TEST_DOCKER_USERNAME_CAMUNDA_CLOUD;
        secret/data/github.com/organizations/camunda NEXUS_PSW | TEST_DOCKER_PASSWORD_CAMUNDA_CLOUD;
  notify:
    name: Send slack notification
    runs-on: ubuntu-latest
    needs: [helm-deploy]
    if: ${{ always() }}
    steps:
      - id: slack-notify-failure
        name: Send failure slack notification
        uses: slackapi/slack-github-action@v2.0.0
        if: ${{ always() && needs.helm-deploy.result != 'success' }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":alarm: *Helm chart Integration Tests* from `main` failed! :alarm:\n"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the related workflow execution: https://github.com/camunda/camunda/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
