name: Slack notification for Java client issue closed
on:
  issues:
    types:
      - closed

jobs:
  slack-notify:
    name: Send slack notification if java client issue has been closed
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'scope/clients-java')
    steps:
      - id: slack-notify
        name: Send slack notification to DevEx
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_DEVEX_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":fyi: A java client issue has been closed at the Zeebe repo. :fyi:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Please check the issue: <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>\n This message has been sent in order to support you in making our other client's feature complete. @sdk-engineers"
                  }
                }
              ]
            }
