name: Operate Check project versions

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch name to check the versions in."
        type: string
        required: true
      releaseVersion:
        description: "Release version to compare to the current Zeebe and Identity versions."
        type: string
        required: true

jobs:
  check_project_versions:
    name: "'${{ inputs.branch }}' branch"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout '${{ inputs.branch }}' branch"
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ inputs.branch }}
          fetch-depth: 0

      - name: Setup Maven
        uses: ./.github/actions/setup-maven-dist
        with:
          maven-version: 3.8.6
          set-mvnw: true

      - name: Check versions
        env:
          RELEASE_VERSION: ${{ inputs.releaseVersion }}
          BRANCH_NAME: ${{ inputs.branch }}
        run: |
          IDENTITY_VERSION=$(./mvnw -f operate help:evaluate -Dexpression=version.identity -q -DforceStdout)

          if [[ $IDENTITY_VERSION != $RELEASE_VERSION ]]; then
            echo "Please update Identity versions!"
            echo "Current Identity version: $IDENTITY_VERSION"
            echo "Both should be updated to: $RELEASE_VERSION"

            exit 1
          fi

          echo "Identity versions are correct!"
