name: Operate Run Test Migrate Elasticsearch Data
on:
  push:
    branches:
      - stable/operate-8.5
jobs:
  run-migration-tests:
    uses: ./.github/workflows/operate-run-tests.yml
    with:
      command: mvn -B -f operate/qa/migration-tests -DskipTests=false verify
    secrets: inherit
