# This GitHub Actions workflow that is triggered on push to `main` and `stable/**` branch or on any pull request creation
# and invokes `ci-build-reusable` and `ci-test-reusable` workflows.
---
name: Tasklist CI
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "stable/**"
  pull_request:

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref == 'refs/heads/main' && github.sha || github.ref) }}

jobs:
  detect-changes:
    outputs:
      tasklist-backend-changes: ${{ steps.filter.outputs.tasklist-backend-changes }}
      tasklist-frontend-changes: ${{ steps.filter.outputs.tasklist-frontend-changes }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      # Detect changes against the base branch
      - name: Detect changes
        uses: ./.github/actions/paths-filter
        id: filter
  run-build:
    name: run-build
    needs: [detect-changes]
    uses: ./.github/workflows/tasklist-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }} # head_ref = branch name on PR, ref_name = `main` or `stable/**`
    if: ${{ needs.detect-changes.outputs.tasklist-backend-changes == 'true' || needs.detect-changes.outputs.tasklist-frontend-changes == 'true' }}

  run-tests:
    name: run-tests
    needs: [detect-changes]
    uses: ./.github/workflows/tasklist-ci-test-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
    if: ${{ needs.detect-changes.outputs.tasklist-backend-changes == 'true' }}
